npm install;
cat >.env <<EOF
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

MAIL_USER=$MAIL_USER
MAIL_PASSWORD=$MAIL_PASSWORD

HOST=$HOST
FRONT_PORT=$FRONT_PORT
BACK_PORT=$BACK_PORT
HASH_SALT=$HASH_SALT

JWT_SECRET=$JWT_SECRET
JWT_EXPIRATION_TIME=$JWT_EXPIRATION_TIME

FT_OAUTH_CLIENT_ID=$FT_OAUTH_CLIENT_ID
FT_OAUTH_CLIENT_SECRET=$FT_OAUTH_CLIENT_SECRET
FT_OAUTH_CALLBACK_URL=$FT_OAUTH_CALLBACK_URL
EOF

if [[ $NODE_ENV == "debug" ]]; then
  npm run start:debug;
elif [[ $NODE_ENV == "check" ]]; then
  npm run format && npm run lint; echo "=== FINISH ===";
else 
  npm run dev;
fi;
